In [ ]:

import numpy as np
image = np.array([[60,113,56,139,85],
                  [73,121,54,84,128],
                  [131,99,70,129,127],
                  [80,57,115,69,134],
                  [104,126,123,95,130]]).reshape(5, 5)
print(image)



[[ 60 113  56 139  85]
 [ 73 121  54  84 128]
 [131  99  70 129 127]
 [ 80  57 115  69 134]
 [104 126 123  95 130]]


In [ ]:
kernel = np.array([[0,-1,0],
                   [-1,5,-1],
                   [0,-1,0]]).reshape(3, 3)
print(kernel)

[[ 0 -1  0]
 [-1  5 -1]
 [ 0 -1  0]]


In [6]:
# how to do elementwise multiplication and sum the result
def convolve2d(image, kernel):
    kernel_height, kernel_width = kernel.shape
    image_height, image_width = image.shape
    pad_height = kernel_height // 2
    pad_width = kernel_width // 2
    padded_image = np.pad(image, ((pad_height, pad_height), (pad_width, pad_width)), mode='constant')
    output = np.zeros_like(image)
    
    for i in range(image_height):
        for j in range(image_width):
            region = padded_image[i:i+kernel_height, j:j+kernel_width]
            output[i, j] = np.sum(region * kernel)
    
    return output

In [7]:
convolve2d(image, kernel)

array([[ 114,  328,  -26,  470,  158],
       [  53,  266,  -61,  -30,  344],
       [ 403,  116,  -47,  295,  244],
       [ 108, -135,  256, -128,  344],
       [ 314,  346,  279,  153,  421]])